spring.application.name=api-gateway
server.port=8080

auth-service.base-url=${AUTH_URL:http://localhost:8081}

routes.auth-service=${AUTH_URL:http://localhost:8081}
routes.ms-pacientes=${MS_PACIENTES_URL:http://localhost:8082}
routes.ms-triaje=${MS_TRIAJE_URL:http://localhost:8083}
routes.ms-cola=${MS_COLA_URL:http://localhost:8084}
routes.ms-atencion=${MS_ATENCION_URL:http://localhost:8085}
routes.ms-admin=${MS_ADMIN_URL:http://localhost:8086}
